# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/harry/cuda-workspace/GPGPU2-Assignment

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/harry/cuda-workspace/GPGPU2-Assignment

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/harry/cuda-workspace/GPGPU2-Assignment/CMakeFiles /home/harry/cuda-workspace/GPGPU2-Assignment/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/harry/cuda-workspace/GPGPU2-Assignment/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named AstroMiner

# Build rule for target.
AstroMiner: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AstroMiner
.PHONY : AstroMiner

# fast build rule for target.
AstroMiner/fast:
	$(MAKE) -f CMakeFiles/AstroMiner.dir/build.make CMakeFiles/AstroMiner.dir/build
.PHONY : AstroMiner/fast

#=============================================================================
# Target rules for targets named AstroCuda

# Build rule for target.
AstroCuda: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AstroCuda
.PHONY : AstroCuda

# fast build rule for target.
AstroCuda/fast:
	$(MAKE) -f cuda/CMakeFiles/AstroCuda.dir/build.make cuda/CMakeFiles/AstroCuda.dir/build
.PHONY : AstroCuda/fast

#=============================================================================
# Target rules for targets named inputreader

# Build rule for target.
inputreader: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 inputreader
.PHONY : inputreader

# fast build rule for target.
inputreader/fast:
	$(MAKE) -f inputfilemanager/reader/CMakeFiles/inputreader.dir/build.make inputfilemanager/reader/CMakeFiles/inputreader.dir/build
.PHONY : inputreader/fast

#=============================================================================
# Target rules for targets named readinputFile

# Build rule for target.
readinputFile: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 readinputFile
.PHONY : readinputFile

# fast build rule for target.
readinputFile/fast:
	$(MAKE) -f inputfilemanager/reader/CMakeFiles/readinputFile.dir/build.make inputfilemanager/reader/CMakeFiles/readinputFile.dir/build
.PHONY : readinputFile/fast

#=============================================================================
# Target rules for targets named inputFileWriter

# Build rule for target.
inputFileWriter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 inputFileWriter
.PHONY : inputFileWriter

# fast build rule for target.
inputFileWriter/fast:
	$(MAKE) -f inputfilemanager/writer/CMakeFiles/inputFileWriter.dir/build.make inputfilemanager/writer/CMakeFiles/inputFileWriter.dir/build
.PHONY : inputFileWriter/fast

AstroMiner.o: AstroMiner.cpp.o
.PHONY : AstroMiner.o

# target to build an object file
AstroMiner.cpp.o:
	$(MAKE) -f CMakeFiles/AstroMiner.dir/build.make CMakeFiles/AstroMiner.dir/AstroMiner.cpp.o
.PHONY : AstroMiner.cpp.o

AstroMiner.i: AstroMiner.cpp.i
.PHONY : AstroMiner.i

# target to preprocess a source file
AstroMiner.cpp.i:
	$(MAKE) -f CMakeFiles/AstroMiner.dir/build.make CMakeFiles/AstroMiner.dir/AstroMiner.cpp.i
.PHONY : AstroMiner.cpp.i

AstroMiner.s: AstroMiner.cpp.s
.PHONY : AstroMiner.s

# target to generate assembly for a file
AstroMiner.cpp.s:
	$(MAKE) -f CMakeFiles/AstroMiner.dir/build.make CMakeFiles/AstroMiner.dir/AstroMiner.cpp.s
.PHONY : AstroMiner.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... AstroMiner"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... AstroCuda"
	@echo "... inputreader"
	@echo "... readinputFile"
	@echo "... inputFileWriter"
	@echo "... AstroMiner.o"
	@echo "... AstroMiner.i"
	@echo "... AstroMiner.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

